### ISSUE TITLE
Let me know how to help out with this

### ISSUE THREAD

**Issue by naupaka** [ashiklom/dbhelpers#1]
Just saw your comment on the SWC blog post. Keen to pitch in to make this work if you are still interested.

**Comment by ashiklom** [comment]
Excellent! Feel free to fork the repo and develop as you see fit -- I'd be more than happy to review and accept pull requests. I probably won't be doing too much active development of this package in the near future, as I only started working on it to assist in another project and the database creation stage of that has ended, but I may be more motivated to develop it if there is outside interest (and especially if there is outside assistance :smile: ).

**Comment by naupaka** [comment]
Yup, I did (fork) and will plan to chip away at it (side project for me too). Thanks for letting me know about the effort :)
